### ISSUE TITLE
[Question] Production ready?

### ISSUE THREAD

**Issue by gabrielginter** [GoogleCloudPlatform/recaptcha-enterprise-flutter#16]
I understand this package is a preview, we have tested it on iOS and Android, seems to work well for us, is anyone using it on a production app, what result did you have?

Hopefully the authors can give their opinion?

Thanks

**Comment by mcorner** [comment]
The underlying sdk is definitely production ready and is in use by very large users. It fits under GCP General Availability (GA). 

The flutter wrapper is relatively new and subject to change (we just changed the API in the last release). It fits under GCP public preview. That said, the wrapper is open source and very thin so it is unlikely to cause problems. 

We always recommend people implement the sdk with a feature flag and at first and monitor it rather than take any immediate action. 

Thanks and good luck.

**Comment by gabrielginter** [comment]
Thanks Mark, indeed I have implemented it with a feature flag, the package seems stable and working well after 4 days in production :)
