### ISSUE TITLE
Not able to see visual checkbox reCAPTCHA 

### ISSUE THREAD

**Issue by cupatil** [GoogleCloudPlatform/recaptcha-enterprise-flutter#48]
We have implemented the reCAPTCHA Enterprise Flutter SDK into our application. We have successfully initialized the client and are able to execute the method and fetch the token from it. However, we are not able to see the visual checkbox reCAPTCHA during this process. Can you please help with this?

**Comment by walterjgsp** [comment]
The mobile SDK do not offer support for visual checkbox as this is the reCaptcha Enterprise version. This is by design to offer the developer the ability to choose the best way to add friction to the user when necessary.

Some alternatives to have the visual checkbox are to use an WebView with reCaptcha web integration that appears in case of low score. An example can be found here https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/tree/main/examples/android/visual
